name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup JBang
        uses: jbangdev/setup-jbang@main
      # Required for the MCP server examples
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Minikube # TODO: Remove once the MCP server is improved to allow for a no-kube-config setup
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube version: 'v1.35.0'
          kubernetes version: 'v1.32.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tests
        run: |
          jbang ./connecting-to-mcp-server-with-langchain4j/LangChainMcpClient.java
          jbang ./kubernetes-patching-resources-from-java/Test.java
          jbang ./kubernetes-rolling-updates-from-java/Test.java
