name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup JBang
        uses: jbangdev/setup-jbang@main
      - name: Tests
        run: |
          jbang ./kubernetes-rolling-updates-from-java/Test.java
